export const GET_FILMS = 'GET_FILMS';
export const LOADING_FILMS = 'LOADING_FILMS';

export const GET_STARSHIPS = 'GET_STARSHIPS';
export const GET_STARSHIPS_DATABASE = 'GET_STARSHIPS_DATABASE'; 
export const GET_STARSHIP = 'GET_STARSHIP';
export const UPDATE_STARSHIP = 'UPDATE_STARSHIP';
export const LOADING_STARSHIPS = 'LOADING_STARSHIPS';
